### ISSUE TITLE
Is there any way to do something like this in nico-nico-twitch Javascript code only?

### ISSUE THREAD

**Issue by TechNeckTV** [loldudester/twitch-emotes#1]
Hello mate!
I recently found a nice nico-nico twitch chat at github. It works like collecting data from twitch chat channel and give it in string format to my local server which works on nodejs. The problem I have I can't replace string for example: 'Kappa' to Kappa.png. The rest is fine but would love that functionality. If you have any idea how to do something like enabling or replacing text with twitch emote in this case I would be grateful. 

The code I used is from: **https://github.com/megalon/Nico-Nico-Twitch**

I asked megalon personally but he doesn't thought about it for now.

**Comment by loldudester** [comment]
I'm not sure I'm the best person to ask really.

Since my code here is a plugin for an existing program with an API that was already capable of doing image insertion, I just had to hook into that. I also mostly copied the code from an existing plugin built into the program.

I'm also not really versed in Javascript, but I'm pretty sure it's far enough removed from Java that none of my work would be particularly helpful.

**Comment by TechNeckTV** [comment]
Ok, thanks for the answer anyways 😃. I will try to code something or ask other people.
